
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int LBRACKET = 42;
  public static final int CONST = 25;
  public static final int ELSIF = 31;
  public static final int NOT_EQUAL = 9;
  public static final int INTEGER = 17;
  public static final int LPAREN = 44;
  public static final int GREATER = 12;
  public static final int ARRAY = 23;
  public static final int LESS = 10;
  public static final int MINUS = 3;
  public static final int WRITE = 20;
  public static final int RPAREN = 45;
  public static final int SEMICOLON = 38;
  public static final int NOT = 16;
  public static final int AND = 15;
  public static final int RECORD = 22;
  public static final int TYPE = 26;
  public static final int OR = 14;
  public static final int COMMA = 40;
  public static final int BEGIN = 35;
  public static final int LESS_EQUAL = 11;
  public static final int ASSIGN = 7;
  public static final int IF = 29;
  public static final int WRITELN = 21;
  public static final int DOT = 41;
  public static final int OF = 37;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int RBRACKET = 43;
  public static final int EQUAL = 8;
  public static final int GREATER_EQUAL = 13;
  public static final int error = 1;
  public static final int ADD = 2;
  public static final int NUMBER = 47;
  public static final int MOD = 6;
  public static final int MODULE = 24;
  public static final int COLON = 39;
  public static final int ELSE = 32;
  public static final int READ = 19;
  public static final int WHILE = 33;
  public static final int THEN = 30;
  public static final int END = 36;
  public static final int MULTI = 4;
  public static final int VAR = 27;
  public static final int PROCEDURE = 28;
  public static final int DO = 34;
  public static final int IDENTIFIER = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ADD",
  "MINUS",
  "MULTI",
  "DIVIDE",
  "MOD",
  "ASSIGN",
  "EQUAL",
  "NOT_EQUAL",
  "LESS",
  "LESS_EQUAL",
  "GREATER",
  "GREATER_EQUAL",
  "OR",
  "AND",
  "NOT",
  "INTEGER",
  "BOOLEAN",
  "READ",
  "WRITE",
  "WRITELN",
  "RECORD",
  "ARRAY",
  "MODULE",
  "CONST",
  "TYPE",
  "VAR",
  "PROCEDURE",
  "IF",
  "THEN",
  "ELSIF",
  "ELSE",
  "WHILE",
  "DO",
  "BEGIN",
  "END",
  "OF",
  "SEMICOLON",
  "COLON",
  "COMMA",
  "DOT",
  "LBRACKET",
  "RBRACKET",
  "LPAREN",
  "RPAREN",
  "IDENTIFIER",
  "NUMBER"
  };
}

