
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface Symbol {
  /* terminals */
  public static final int LBRACKET = 30;
  public static final int CONST = 20;
  public static final int ELSIF = 19;
  public static final int NOT_EQUAL = 33;
  public static final int INTEGER = 2;
  public static final int GREATER = 37;
  public static final int LPAREN = 28;
  public static final int ARRAY = 4;
  public static final int MINUS = 39;
  public static final int LESS = 35;
  public static final int WRITE = 6;
  public static final int RPAREN = 29;
  public static final int NOT = 45;
  public static final int AND = 43;
  public static final int SEMICOLON = 27;
  public static final int RECORD = 5;
  public static final int TYPE = 22;
  public static final int OR = 44;
  public static final int COMMA = 24;
  public static final int DIV = 41;
  public static final int BEGIN = 12;
  public static final int LESS_EQUAL = 34;
  public static final int ASSIGN = 23;
  public static final int IF = 14;
  public static final int WRITELN = 7;
  public static final int DOT = 25;
  public static final int OF = 9;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RBRACKET = 31;
  public static final int EQUAL = 32;
  public static final int GREATER_EQUAL = 36;
  public static final int error = 1;
  public static final int MUL = 40;
  public static final int ADD = 38;
  public static final int NUMBER = 47;
  public static final int MOD = 42;
  public static final int MODULE = 21;
  public static final int COLON = 26;
  public static final int ELSE = 16;
  public static final int READ = 8;
  public static final int WHILE = 17;
  public static final int THEN = 15;
  public static final int END = 13;
  public static final int VAR = 10;
  public static final int PROCEDURE = 11;
  public static final int DO = 18;
  public static final int IDENTIFIER = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "BOOLEAN",
  "ARRAY",
  "RECORD",
  "WRITE",
  "WRITELN",
  "READ",
  "OF",
  "VAR",
  "PROCEDURE",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "ELSIF",
  "CONST",
  "MODULE",
  "TYPE",
  "ASSIGN",
  "COMMA",
  "DOT",
  "COLON",
  "SEMICOLON",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "EQUAL",
  "NOT_EQUAL",
  "LESS_EQUAL",
  "LESS",
  "GREATER_EQUAL",
  "GREATER",
  "ADD",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "IDENTIFIER",
  "NUMBER"
  };
}

